version: '3.3'

services:
  php-fpm:
    container_name: "php-fpm"
    build: ./
    ports:
      - 5000:8000
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql
    container_name: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tkt
  mysql_test:
    image: 'mysql'
    container_name: "mysql_test"
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
        - '3306'
  phpmyadmin:
    container_name: "phpMyAdmin"
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
